.TH "NSString(RemoveEmoji)" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSString(RemoveEmoji)
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(BOOL) \- \fBisIncludingEmoji\fP"
.br
.ti -1c
.RI "(instancetype) \- \fBstringByRemovingEmoji\fP"
.br
.ti -1c
.RI "((deprecated) \- \fB__attribute__\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
