.TH "NSString(XcodeMemberTypeExtensions)" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSString(XcodeMemberTypeExtensions)
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(XcodeMemberType) \- \fBxce_asMemberType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasFileReferenceType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasFileReferenceOrReferenceProxyType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasReferenceProxyType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasGroupType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasProjectType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasNativeTargetType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasBuildFileType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasBuildConfigurationType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasContainerItemProxyType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasResourcesBuildPhaseType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasShellScriptBuildPhase\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasSourcesOrFrameworksBuildPhaseType\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBxce_hasVersionedGroupType\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(NSString *) + \fBxce_stringFromMemberType:\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
