.TH "NSString(XcodeSourceTreeTypeExtensions)" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSString(XcodeSourceTreeTypeExtensions)
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(XcodeSourceTreeType) \- \fBxce_asSourceTreeType\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(NSString *) + \fBxce_stringFromSourceTreeType:\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
