.TH "XCAbstractDefinition" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCAbstractDefinition
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <XCAbstractDefinition\&.h>\fP
.PP
Inherits NSObject\&.
.PP
Inherited by \fBXCBuildShellScriptDefinition\fP, \fBXCClassDefinition\fP, \fBXCFrameworkDefinition\fP, \fBXCSourceFileDefinition\fP, \fBXCSubProjectDefinition\fP, and \fBXCXibDefinition\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "XCFileOperationType \fB_fileOperationType\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "XCFileOperationType \fBfileOperationType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds properties to all types of resource that can be added to an Xcode project\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
