.TH "XCBuildShellScript" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCBuildShellScript
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(instancetype _Nonnull) \- \fBinitWithProject:key:name:files:inputPaths:outputPaths:runOnlyForDeploymentPostprocessing:shellPath:shellScript:\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(\fBXCBuildShellScript\fP *_Nonnull) + \fBshellScriptWithProject:key:name:files:inputPaths:outputPaths:runOnlyForDeploymentPostprocessing:shellPath:shellScript:\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSString * \fB_key\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBkey\fP"
.br
.ti -1c
.RI "NSString * \fBname\fP"
.br
.ti -1c
.RI "BOOL \fBrunOnlyForDeploymentPostprocessing\fP"
.br
.ti -1c
.RI "NSString * \fBshellScript\fP"
.br
.ti -1c
.RI "NSString * \fBshellPath\fP"
.br
.ti -1c
.RI "NSArray< NSString * > * \fBfiles\fP"
.br
.ti -1c
.RI "NSArray< NSString * > * \fBinputPaths\fP"
.br
.ti -1c
.RI "NSArray< NSString * > * \fBoutputPaths\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
