.TH "<XCBuildFile>" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<XCBuildFile>
.SH SYNOPSIS
.br
.PP
.PP
Inherits <NSObject>\&.
.PP
Inherited by \fBXCGroup\fP, \fBXCSourceFile\fP, and \fBXCVersionGroup\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) \- \fBbecomeBuildFile\fP"
.br
.ti -1c
.RI "(XcodeMemberType) \- \fBbuildPhase\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBbuildFileKey\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBisBuildFile\fP"
.br
.in -1c
.SH "Method Documentation"
.PP 
.SS "\- (void) becomeBuildFile "

.PP
Reimplemented in \fBXCSourceFile\fP\&.
.SS "\- (BOOL) isBuildFile "

.PP
Reimplemented in \fBXCSourceFile\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
