.TH "XCFileOperationQueue" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCFileOperationQueue
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBinitWithBaseDirectory:\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBfileWithName:existsInProjectDirectory:\fP"
.br
.ti -1c
.RI "(void) \- \fBqueueTextFile:inDirectory:withContents:\fP"
.br
.ti -1c
.RI "(void) \- \fBqueueDataFile:inDirectory:withContents:\fP"
.br
.ti -1c
.RI "(void) \- \fBqueueFrameworkWithFilePath:inDirectory:\fP"
.br
.ti -1c
.RI "(void) \- \fBqueueDeletion:\fP"
.br
.ti -1c
.RI "(void) \- \fBqueueDirectory:inDirectory:\fP"
.br
.ti -1c
.RI "(void) \- \fBcommitFileOperations\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
