.TH "XCFileOperationQueue()" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCFileOperationQueue()
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(NSString *) \- \fBdestinationPathFor:inProjectDirectory:\fP"
.br
.ti -1c
.RI "(void) \- \fBperformFileWrites\fP"
.br
.ti -1c
.RI "(void) \- \fBperformCopyFrameworks\fP"
.br
.ti -1c
.RI "(void) \- \fBperformFileDeletions\fP"
.br
.ti -1c
.RI "(void) \- \fBperformCreateDirectories\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
