.TH "XCFrameworkDefinition" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCFrameworkDefinition
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBXCAbstractDefinition\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBinitWithFilePath:copyToDestination:\fP"
.br
.ti -1c
.RI "(id) \- \fBinitWithFilePath:copyToDestination:sourceTree:\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBfileName\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(\fBXCFrameworkDefinition\fP *) + \fBframeworkDefinitionWithFilePath:copyToDestination:\fP"
.br
.ti -1c
.RI "(\fBXCFrameworkDefinition\fP *) + \fBframeworkDefinitionWithFilePath:copyToDestination:sourceTree:\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSString * \fB_filePath\fP"
.br
.ti -1c
.RI "BOOL \fB_copyToDestination\fP"
.br
.ti -1c
.RI "XcodeSourceTreeType \fB_sourceTree\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBfilePath\fP"
.br
.ti -1c
.RI "BOOL \fBcopyToDestination\fP"
.br
.ti -1c
.RI "XcodeSourceTreeType \fBsourceTree\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
