.TH "XCKeyBuilder" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCKeyBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBinitHashValueMD5HashWithBytes:length:\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBbuild\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(\fBXCKeyBuilder\fP *) + \fBforItemNamed:\fP"
.br
.ti -1c
.RI "(\fBXCKeyBuilder\fP *) + \fBcreateUnique\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fB_value\fP [HASH_VALUE_STORAGE_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
