.TH "<XcodeGroupMember>" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<XcodeGroupMember>
.SH SYNOPSIS
.br
.PP
.PP
Inherits <NSObject>\&.
.PP
Inherited by \fBXCGroup\fP, \fBXCSourceFile\fP, and \fBXCVersionGroup\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(NSString *) \- \fBkey\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBdisplayName\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBpathRelativeToProjectRoot\fP"
.br
.ti -1c
.RI "(XcodeMemberType) \- \fBgroupMemberType\fP"
.br
.in -1c
.SH "Method Documentation"
.PP 
.SS "\- (XcodeMemberType) groupMemberType "
Group members can either be other groups (PBXGroup) or source files (PBXFileReference)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
