.TH "XCProject(SubProject)" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCProject(SubProject)
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(NSString *) \- \fBreferenceProxyKeyForName:\fP"
.br
.ti -1c
.RI "(NSArray< \fBXCSourceFile\fP * > *) \- \fBbuildProductsForTargets:\fP"
.br
.ti -1c
.RI "(void) \- \fBaddAsTargetDependency:toTargets:\fP"
.br
.ti -1c
.RI "(NSArray< NSString * > *) \- \fBkeysForProjectObjectsOfType:withIdentifier:singleton:required:\fP"
.br
.ti -1c
.RI "(NSMutableDictionary *) \- \fBPBXProjectDict\fP"
.br
.ti -1c
.RI "(void) \- \fBremoveProxies:\fP"
.br
.ti -1c
.RI "(void) \- \fBaddProxies:\fP"
.br
.ti -1c
.RI "(void) \- \fBremoveFromProjectReferences:forProductsGroup:\fP"
.br
.ti -1c
.RI "(void) \- \fBremoveTargetDependencies:\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBcontainerItemProxyKeyForName:proxyType:\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBproductsGroupKeyForKey:\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
