.TH "XCSourceFile" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCSourceFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <XCSourceFile\&.h>\fP
.PP
Inherits NSObject, \fB<XcodeGroupMember>\fP, and \fB<XCBuildFile>\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBinitWithProject:key:type:name:sourceTree:path:\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBisBuildFile\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBcanBecomeBuildFile\fP"
.br
.ti -1c
.RI "(XcodeMemberType) \- \fBbuildPhase\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBbuildFileKey\fP"
.br
.ti -1c
.RI "(void) \- \fBbecomeBuildFile\fP"
.br
.ti -1c
.RI "(void) \- \fBremoveBuildFile\fP"
.br
.ti -1c
.RI "(void) \- \fBsetCompilerFlags:\fP"
.br
.ti -1c
.RI "(void) \- \fBsetWeakReference\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(\fBXCSourceFile\fP *) + \fBsourceFileWithProject:key:type:name:sourceTree:path:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "XcodeSourceFileType \fBtype\fP"
.br
.ti -1c
.RI "NSString * \fBkey\fP"
.br
.ti -1c
.RI "NSString * \fBname\fP"
.br
.ti -1c
.RI "NSString * \fBsourceTree\fP"
.br
.ti -1c
.RI "NSString * \fBpath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a file resource in an xcode project\&. 
.SH "Method Documentation"
.PP 
.SS "\- (void) becomeBuildFile "
Adds this file to the project as an \fCxcode_BuildFile\fP, ready to be included in targets\&. 
.PP
Reimplemented from \fB<XCBuildFile>\fP\&.
.SS "\- (NSString *) buildFileKey "

.PP
Reimplemented from \fB<XCBuildFile>\fP\&.
.SS "\- (XcodeMemberType) buildPhase "

.PP
Reimplemented from \fB<XCBuildFile>\fP\&.
.SS "\- (BOOL) isBuildFile "
If yes, indicates the file is able to be included for compilation in an \fC\fBXCTarget\fP\fP\&. 
.PP
Reimplemented from \fB<XCBuildFile>\fP\&.
.SS "\- (void) removeBuildFile "
Removes this file as an \fCxcode_BuildFile\fP from the project\&. 
.SS "\- (void) setCompilerFlags: (NSString *) value"
Method for setting Compiler Flags for individual build files
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP String value to set in Compiler Flags 
.RE
.PP

.SS "\- (void) setWeakReference "
Method for setting the build file is a weak reference 

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
