.TH "XCSourceFileDefinition" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCSourceFileDefinition
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBXCAbstractDefinition\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBinitWithName:text:type:\fP"
.br
.ti -1c
.RI "(id) \- \fBinitWithName:data:type:\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(\fBXCSourceFileDefinition\fP *) + \fBsourceDefinitionWithName:text:type:\fP"
.br
.ti -1c
.RI "(\fBXCSourceFileDefinition\fP *) + \fBsourceDefinitionWithName:data:type:\fP"
.br
.ti -1c
.RI "(\fBXCSourceFileDefinition\fP *) + \fBsourceDefinitionWithAssetCatalogName:\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSString * \fB_sourceFileName\fP"
.br
.ti -1c
.RI "XcodeSourceFileType \fB_type\fP"
.br
.ti -1c
.RI "NSData * \fB_data\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBsourceFileName\fP"
.br
.ti -1c
.RI "NSData * \fBdata\fP"
.br
.ti -1c
.RI "XcodeSourceFileType \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
