.TH "XCXibDefinition" 3 "Fri Mar 4 2022" "Version 1.1" "XcodeEditor-master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCXibDefinition
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBXCAbstractDefinition\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBinitWithName:\fP"
.br
.ti -1c
.RI "(id) \- \fBinitWithName:content:\fP"
.br
.ti -1c
.RI "(NSString *) \- \fBxibFileName\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(\fBXCXibDefinition\fP *) + \fBxibDefinitionWithName:\fP"
.br
.ti -1c
.RI "(\fBXCXibDefinition\fP *) + \fBxibDefinitionWithName:content:\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSString * \fB_name\fP"
.br
.ti -1c
.RI "NSString * \fB_content\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBname\fP"
.br
.ti -1c
.RI "NSString * \fBcontent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XcodeEditor-master from the source code\&.
